name: Main branch merge tests
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 21.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Modules
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build Project
        run: npm run build:vite
      - name: Start Storybook
        run: npm run dev:storybook
      - name: Run Storybook Tests
        run: npm run test:storybook
      - name: Run Unit Tests
        run: npm run test:unit
      - name: Run E2E Tests
        run: npm run test:playwright
      - name: Lint Code
        run: npm run lint